[functions]
  directory = "netlify2/functions"

[[headers]]
  for = "/src/*.tsx"
    [headers.values]
      Content-Type = "application/javascript"

[[headers]]
  for = "/src/*.js"
    [headers.values]
      Content-Type = "application/javascript"
